env:
  browser: true
  es2021: true
extends: [
  "eslint:recommended",
  "plugin:react-hooks/recommended",
  "plugin:import/recommended"
],

overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: moduler

rules: 
import/extensions: "off"
  no-console: "off"
  no-var: "error"
  import/extensions: 
    - error
    - js: always

